name: Deploy

on: [push]

jobs:
  resume-action:
    runs-on: ubuntu-latest
    name: Resume Action Job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Resume Action Step
        id: resume-step
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          directory: 'data'
          cname: 'test.r3ck.com.br'